fos_rest:
    view:
        view_response_listener:  true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
            - { path: '^/', priorities: ['html', 'json', '*/*'], fallback_format: html, prefer_extension: false }

#    exception:
#      exception_controller: 'fos_rest.exception.controller:showAction'
#      codes:
#          Doctrine\ORM\EntityNotFoundException: 404
#         \LogicException: 400
